name: "Pipeline Security Engine"
description: "Visibility and control over all the network activity from your pipeline."

inputs:
  github-token:
    description: "github token"
    required: true
  VB_API_URL:
    description: 'VB API URL'
    required: true
  VB_API_KEY:
    description: 'VB API Key'
    required: true

branding:
  icon: bell
  color: green

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        VB_API_URL: ${{ inputs.VB_API_URL }}
        VB_API_KEY: ${{ inputs.VB_API_KEY }}
      run: ./pse-action.sh

    - shell: bash
      if: always()
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        VB_API_URL: ${{ inputs.VB_API_URL }}
        VB_API_KEY: ${{ inputs.VB_API_KEY }}
      run: ./cleanup.sh