pipeline {
    agent {
        docker { image 'golang'
            args "-u root:sudo --network build_agents"
        }
    }
 

    stages {
     
        stage('pse') {
            steps {
                script {
                    pse.start()
                }
              
            }
        }
           stage('checkout') {
            steps {
                checkout scm
            }
        }
         stage('git') {
            steps {
                sh(script: 'rm -rf coveralls-public cobra tor')
                //sh(script: 'git clone https://github.com/lemurheavy/coveralls-public')
                sh(script: 'git clone https://github.com/torproject/tor')

            }
        }
        
        
        stage('npm') {
            steps {
                sh(script: 'rm -rf node_modules')
                sh(script: 'apt-get update')
                sh(script: 'apt-get -qq -y install npm')
                sh(script: 'npm install color-name')
            }
        }
        
        stage('web') {
            steps {
                sh(script: 'curl https://wetransfer.com/')
            }
        }
        
        stage('go') {
            steps {
	       sh(script: 'rm -rf go.mod')
               sh(script: 'go mod init demo.invisirisk/psedemo')
               sh(script: 'go get golang.org/x/text')

            }
        }
    }
    post {
            always {
                script {
                    pse.end()
                }
            }
    }
    
}

