name: NPM Build Demo

on:
  push:
  pull_request:

permissions:
  checks: write
  contents: read
  packages: read
  
jobs:
  build:
    services:
      # Label used to access the service container
      pse:
        image: invisirisk/pse:latest
        #env:
           #POLICY_AUTH_TOKEN: ${{ secrets.POLICY_AUTH_TOKEN }}
           #POLICY_URL: https://api.github.com/repos/invisirisk/policy/tarball/main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           #OPENAI_AUTH_TOKEN: ${{ secrets.OPENAI_AUTH_TOKEN }}
           #PSE_DEBUG_FLAG: --alsologtostderr
           #POLICY_LOG: t
    container:
      image: node:19-alpine
      options: --cap-add=NET_ADMIN
      
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    
    steps:
      - run: apk add make git
      - uses: invisirisk/pse-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: cd demo/npm && make
        env:
           IR_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The build uses private NPM registry
